require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PdfXmlMappingsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PdfXmlMapping. As you add validations to PdfXmlMapping, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PdfXmlMappingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pdf_xml_mappings as @pdf_xml_mappings" do
      pdf_xml_mapping = PdfXmlMapping.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:pdf_xml_mappings)).to eq([pdf_xml_mapping])
    end
  end

  describe "GET show" do
    it "assigns the requested pdf_xml_mapping as @pdf_xml_mapping" do
      pdf_xml_mapping = PdfXmlMapping.create! valid_attributes
      get :show, {:id => pdf_xml_mapping.to_param}, valid_session
      expect(assigns(:pdf_xml_mapping)).to eq(pdf_xml_mapping)
    end
  end

  describe "GET new" do
    it "assigns a new pdf_xml_mapping as @pdf_xml_mapping" do
      get :new, {}, valid_session
      expect(assigns(:pdf_xml_mapping)).to be_a_new(PdfXmlMapping)
    end
  end

  describe "GET edit" do
    it "assigns the requested pdf_xml_mapping as @pdf_xml_mapping" do
      pdf_xml_mapping = PdfXmlMapping.create! valid_attributes
      get :edit, {:id => pdf_xml_mapping.to_param}, valid_session
      expect(assigns(:pdf_xml_mapping)).to eq(pdf_xml_mapping)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PdfXmlMapping" do
        expect {
          post :create, {:pdf_xml_mapping => valid_attributes}, valid_session
        }.to change(PdfXmlMapping, :count).by(1)
      end

      it "assigns a newly created pdf_xml_mapping as @pdf_xml_mapping" do
        post :create, {:pdf_xml_mapping => valid_attributes}, valid_session
        expect(assigns(:pdf_xml_mapping)).to be_a(PdfXmlMapping)
        expect(assigns(:pdf_xml_mapping)).to be_persisted
      end

      it "redirects to the created pdf_xml_mapping" do
        post :create, {:pdf_xml_mapping => valid_attributes}, valid_session
        expect(response).to redirect_to(PdfXmlMapping.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pdf_xml_mapping as @pdf_xml_mapping" do
        post :create, {:pdf_xml_mapping => invalid_attributes}, valid_session
        expect(assigns(:pdf_xml_mapping)).to be_a_new(PdfXmlMapping)
      end

      it "re-renders the 'new' template" do
        post :create, {:pdf_xml_mapping => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pdf_xml_mapping" do
        pdf_xml_mapping = PdfXmlMapping.create! valid_attributes
        put :update, {:id => pdf_xml_mapping.to_param, :pdf_xml_mapping => new_attributes}, valid_session
        pdf_xml_mapping.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pdf_xml_mapping as @pdf_xml_mapping" do
        pdf_xml_mapping = PdfXmlMapping.create! valid_attributes
        put :update, {:id => pdf_xml_mapping.to_param, :pdf_xml_mapping => valid_attributes}, valid_session
        expect(assigns(:pdf_xml_mapping)).to eq(pdf_xml_mapping)
      end

      it "redirects to the pdf_xml_mapping" do
        pdf_xml_mapping = PdfXmlMapping.create! valid_attributes
        put :update, {:id => pdf_xml_mapping.to_param, :pdf_xml_mapping => valid_attributes}, valid_session
        expect(response).to redirect_to(pdf_xml_mapping)
      end
    end

    describe "with invalid params" do
      it "assigns the pdf_xml_mapping as @pdf_xml_mapping" do
        pdf_xml_mapping = PdfXmlMapping.create! valid_attributes
        put :update, {:id => pdf_xml_mapping.to_param, :pdf_xml_mapping => invalid_attributes}, valid_session
        expect(assigns(:pdf_xml_mapping)).to eq(pdf_xml_mapping)
      end

      it "re-renders the 'edit' template" do
        pdf_xml_mapping = PdfXmlMapping.create! valid_attributes
        put :update, {:id => pdf_xml_mapping.to_param, :pdf_xml_mapping => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pdf_xml_mapping" do
      pdf_xml_mapping = PdfXmlMapping.create! valid_attributes
      expect {
        delete :destroy, {:id => pdf_xml_mapping.to_param}, valid_session
      }.to change(PdfXmlMapping, :count).by(-1)
    end

    it "redirects to the pdf_xml_mappings list" do
      pdf_xml_mapping = PdfXmlMapping.create! valid_attributes
      delete :destroy, {:id => pdf_xml_mapping.to_param}, valid_session
      expect(response).to redirect_to(pdf_xml_mappings_url)
    end
  end

end
